eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10101/eureka
    metadata-map:
      user.name: jbone
      user.password: jbone
  instance:
    prefer-ip-address: true
    instance-id: http://${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: jbone
      user.password: jbone
server:
  port: 18443
spring:
  application:
    name: jbone-gateway
management:
  security:
    enabled: false
zuul:
  routes:
    authorization:
      path: /**
      serviceId: Jbone-CAS
    sm-admin:
      path: /222/**
      serviceId: jbone-sm-admin
  MyPreFilter2:
    pre:
      disable: true
  retryable: true  #是否开启重试功能
ribbon:                           #注意:断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
  MaxAutoRetries: 1              #对当前服务的重试次数 如果设置为1那么就是1+1=2.如果设置3那么就是3次
  MaxAutoRetriesNextServer: 1    #切换相同Server的次数

##zuul
#zuul.max.host.connections=500
#zuul.host.socket-timeout-millis=60000
#zuul.host.connect-timeout-millis=60000
#
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=60000
#ribbon.ConnectTimeout=3000
#ribbon.ReadTimeout=60000
#
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=5