serivcename: http://localhost:8444
server:
  port: 8444
cas:
  server:
    name: {serivcename}
    prefix: ${serivcename}/cas
logging:
  config: classpath:log4j2_server2.xml
spring.boot.admin.client:
  management-base-url: ${serivcename}/cas
  management-url: ${spring.boot.admin.client.management-base-url}
  service-url: ${spring.boot.admin.client.management-base-url}